/*************************************************************\
|                           LuaHypArc                         |
|                      ==================                     |
|                   An extension of LUAppArc                  |
|                                                             |
|                     luahyparc.zapto.org                     |
\*************************************************************/


/************************************************************************/
/* SCRIPT FUNCTION TABLES                                               */
/************************************************************************/

RegType<Item> ItemMethods[] = {
    // Item Gossip functions
    { "GossipCreateMenu", &luaItem::GossipCreateMenu },
	{ "GossipMenuAddItem", &luaItem::GossipMenuAddItem },
	{ "GossipSendMenu", &luaItem::GossipSendMenu },
	{ "GossipComplete", &luaItem::GossipComplete },
	{ "GossipSendPOI", &luaItem::GossipSendPOI },
	{ "PerformWorldDBQuery", &luaItem::PerformWorldDBQuery },
	{ "PerformCharDBQuery", &luaItem::PerformCharDBQuery },
	{ "GetOwner", &luaItem::GetOwner },
	{ "AddEnchantment", &luaItem::AddEnchantment },
	{ "RemoveEnchantment", &luaItem::RemoveEnchantment },
	//hypersniper added commands
	{ "GetEntryId", &luaItem::GetEntryId },
	{ "GetName", &luaItem::GetName },
	{ "GetSpellId", &luaItem::GetSpellId },
	{ "GetSpellTrigger", &luaItem::GetSpellTrigger },
	{ "GetGUID", &luaItem::GetGUID },
	{ "GetRawGUID", &luaItem::GetRawGUID },
	{ "AddLoot", &luaItem::AddLoot},
	{ NULL, NULL },
};




RegType<Unit> UnitMethods[] = {
	{ "GossipCreateMenu", &luaUnit::GossipCreateMenu },
	{ "GossipMenuAddItem", &luaUnit::GossipMenuAddItem },
	{ "GossipSendMenu", &luaUnit::GossipSendMenu },
	{ "GossipComplete", &luaUnit::GossipComplete },
	{ "GossipSendPOI", &luaUnit::GossipSendPOI },
	{ "GetName", &luaUnit::GetName },
	{ "SendChatMessage", &luaUnit::SendChatMessage },
	{ "MoveTo", &luaUnit::MoveTo },
	{ "SetMovementType", &luaUnit::SetMovementType },
	{ "CastSpell", &luaUnit::CastSpell },
	{ "FullCastSpell", &luaUnit::FullCastSpell },
	{ "FullCastSpellOnTarget", &luaUnit::FullCastSpellOnTarget },
	{ "SpawnCreature", &luaUnit::SpawnCreature },
	{ "SpawnGameObject", &luaUnit::SpawnGameObject },
	{ "GetX", &luaUnit::GetX },
	{ "GetY", &luaUnit::GetY },
	{ "GetZ", &luaUnit::GetZ },
	{ "GetO", &luaUnit::GetO },
	{ "IsPlayer", &luaUnit::IsPlayer },
	{ "IsCreature", &luaUnit::IsCreature },
	{ "RegisterEvent", &luaUnit::RegisterEvent },
	{ "RemoveEvents", &luaUnit::RemoveEvents },
	{ "SendBroadcastMessage", &luaUnit::SendBroadcastMessage },
	{ "SendAreaTriggerMessage", &luaUnit::SendAreaTriggerMessage },
	{ "KnockBack", &luaUnit::KnockBack },
	{ "MarkQuestObjectiveAsComplete", &luaUnit::MarkQuestObjectiveAsComplete },
	{ "LearnSpell", &luaUnit::LearnSpell },
	{ "UnlearnSpell", &luaUnit::UnlearnSpell },
	{ "HasFinishedQuest", &luaUnit::HasFinishedQuest },
	{ "GetItemCount", &luaUnit::GetItemCount },
	{ "IsInCombat", &luaUnit::IsInCombat },
	{ "GetMainTank", &luaUnit::GetMainTank },
	{ "GetAddTank", &luaUnit::GetAddTank },
	{ "ClearThreatList", &luaUnit::ClearThreatList },
	{ "GetTauntedBy", &luaUnit::GetTauntedBy },
	{ "SetTauntedBy", &luaUnit::SetTauntedBy },
	{ "SetSoulLinkedWith", &luaUnit::SetSoulLinkedWith },
	{ "GetSoulLinkedWith", &luaUnit::GetSoulLinkedWith },
	{ "ChangeTarget", &luaUnit::ChangeTarget },
	{ "GetHealthPct", &luaUnit::GetHealthPct },
	{ "SetHealthPct", &luaUnit::SetHealthPct },
	{ "GetManaPct", &luaUnit::GetManaPct },
	{ "Despawn", &luaUnit::Despawn },
	{ "GetUnitBySqlId", &luaUnit::GetUnitBySqlId },
	{ "PlaySoundToSet", &luaUnit::PlaySoundToSet },
	{ "RemoveAura", &luaUnit::RemoveAura },
	{ "StopMovement", &luaUnit::StopMovement },
	{ "Emote", &luaUnit::Emote },
	{ "GetInstanceID", &luaUnit::GetInstanceID },
	{ "GetClosestPlayer", &luaUnit::GetClosestPlayer },
	{ "GetRandomPlayer", &luaUnit::GetRandomPlayer },
	{ "GetRandomFriend", &luaUnit::GetRandomFriend },
	{ "GetRandomEnemy", &luaUnit::GetRandomEnemy },
	{ "AddItem", &luaUnit::AddItem },
	{ "RemoveItem", &luaUnit::RemoveItem },
	{ "CreateCustomWaypointMap", &luaUnit::CreateCustomWaypointMap },
	{ "CreateWaypoint", &luaUnit::CreateWaypoint },
	{ "MoveToWaypoint", &luaUnit::MoveToWaypoint },
	{ "DestroyCustomWaypointMap", &luaUnit::DestroyCustomWaypointMap },
	{ "SetCombatCapable", &luaUnit::SetCombatCapable },
	{ "SetCombatMeleeCapable", &luaUnit::SetCombatMeleeCapable },
	{ "SetCombatRangedCapable", &luaUnit::SetCombatRangedCapable },
	{ "SetCombatSpellCapable", &luaUnit::SetCombatSpellCapable },
	{ "SetCombatTargetingCapable", &luaUnit::SetCombatTargetingCapable },
	{ "SetNPCFlags", &luaUnit::SetNPCFlags },
	{ "SetModel", &luaUnit::SetModel },
	{ "SetScale", &luaUnit::SetScale },
	{ "SetFaction", &luaUnit::SetFaction },
	{ "SetStandState",&luaUnit::SetStandState },
	{ "Teleport" , &luaUnit::TeleportUnit },
	{ "GetPlayerClass", &luaUnit::GetPlayerClass },
	{ "ClearThreatList", &luaUnit::ClearHateList },
	{ "WipeThreatList", &luaUnit::WipeHateList },
	{ "WipeTargetList", &luaUnit::WipeTargetList },
	{ "WipeCurrentTarget", &luaUnit::WipeCurrentTarget },
	{ "GetHealth", &luaUnit::GetHealth },
	{ "GetMaxHealth", &luaUnit::GetMaxHealth },
	{ "SetHealth", &luaUnit::SetHealth },
	{ "SetMaxHealth", &luaUnit::SetMaxHealth },
	{ "HasAura", &luaUnit::HasAura },
	{ "Land", &luaUnit::Land },
	{ "SetFlying", &luaUnit::SetFlying },
	{ "SetMana", &luaUnit::SetMana },
	{ "SetMaxMana", &luaUnit::SetMaxMana },
	{ "GetDistance", &luaUnit::GetDistance },
	{ "GetGUID", &luaUnit::GetGUID },
	{ "GetCreatureNearestCoords", &luaUnit::GetCreatureNearestCoords },
    { "CastSpellAoF", &luaUnit::CastSpellAoF },
	{ "GetGameObjectNearestCoords", &luaUnit::GetGameObjectNearestCoords },
	{ "SetInFront", &luaUnit::SetInFront },
	{ "RemoveAllAuras", &luaUnit::RemoveAllAuras },
	{ "ReturnToSpawnPoint", &luaUnit::ReturnToSpawnPoint },
	{ "CancelSpell", &luaUnit::CancelSpell },
	{ "IsAlive", &luaUnit::IsAlive },
	{ "IsDead", &luaUnit::IsDead },
	{ "IsInWorld", &luaUnit::IsInWorld },
	{ "GetZoneId", &luaUnit::GetZoneId },
	{ "GetMana", &luaUnit::GetMana },
	{ "GetMaxMana", &luaUnit::GetMaxMana },
	{ "Root", &luaUnit::Root },
	{ "Unroot", &luaUnit::Unroot },
	{ "IsCreatureMoving", &luaUnit::IsCreatureMoving },
	{ "SetOutOfCombatRange", &luaUnit::SetOutOfCombatRange },
	{ "ModifyRunSpeed", &luaUnit::ModifyRunSpeed },
	{ "ModifyWalkSpeed", &luaUnit::ModifyWalkSpeed },
	{ "ModifyFlySpeed" , &luaUnit::ModifyFlySpeed },
	{ "GetCurrentSpell", &luaUnit::GetCurrentSpell },
	{ "IsFlying", &luaUnit::IsFlying },
	{ "SetRotation", &luaUnit::SetRotation },
	{ "SetOrientation", &luaUnit::SetOrientation },
	{ "GetSpawnX", &luaUnit::GetSpawnX },
	{ "GetSpawnY", &luaUnit::GetSpawnY },
	{ "GetSpawnZ", &luaUnit::GetSpawnZ },
	{ "GetSpawnO", &luaUnit::GetSpawnO },
	{ "GetInRangePlayersCount", &luaUnit::GetInRangePlayersCount },
	{ "GetEntry", &luaUnit::GetEntry },
	{ "SetMoveRunFlag", &luaUnit::SetMoveRunFlag },
	{ "GetAIState", &luaUnit::GetAIState },
	{ "ModUInt32Value", &luaUnit::ModUInt32Value },
	{ "ModFloatValue", &luaUnit::ModFloatValue },
	{ "SetUInt32Value", &luaUnit::SetUInt32Value },
	{ "SetUInt64Value", &luaUnit::SetUInt64Value },
	{ "SetFloatValue", &luaUnit::SetFloatValue },
	{ "GetUInt32Value", &luaUnit::GetUInt32Value },
	{ "GetUInt64Value", &luaUnit::GetUInt64Value },
	{ "GetFloatValue", &luaUnit::GetFloatValue },
	{ "InitPacket", &luaUnit::InitPacket },
	{ "AddDataToPacket", &luaUnit::AddDataToPacket },
	{ "AddGuidDataToPacket", &luaUnit::AddGuidDataToPacket },
	{ "SendPacketToSet", &luaUnit::SendPacketToSet },
	{ "AdvanceQuestObjective", &luaUnit::AdvanceQuestObjective },
	{ "Heal", &luaUnit::Heal },
	{ "Energize", &luaUnit::Energize },
	{ "SendChatMessageAlternateEntry", &luaUnit::SendChatMessageAlternateEntry },
	{ "SendChatMessageToPlayer", &luaUnit::SendChatMessageToPlayer },
	{ "SetPowerType", &luaUnit::SetPowerType },
	{ "Strike", &luaUnit::Strike },
	{ "SetAttackTimer", &luaUnit::SetAttackTimer },
	{ "Kill", &luaUnit::Kill },
	{ "DealDamage", &luaUnit::DealDamage },
	{ "IsInFront", &luaUnit::IsInFront },
	{ "IsInBack", &luaUnit::IsInBack },
	{ "IsPacified", &luaUnit::IsPacified },
	{ "IsStunned", &luaUnit::IsStunned },
	{ "IsFeared", &luaUnit::IsFeared },
	{ "CreateGuardian", &luaUnit::CreateGuardian },
	{ "HandleEvent", &luaUnit::HandleEvent },
	{ "HasInRangeObjects", &luaUnit::HasInRangeObjects },
	{ "IsInWater", &luaUnit::IsInWater },
	{ "IsInArc", &luaUnit::IsInArc },
	{ "GetInRangeObjects", &luaUnit::GetInRangeGameObjects },
	{ "GetInRangeObjectsCount", &luaUnit::GetInRangeObjectsCount },
	{ "GetAITargetsCount", &luaUnit::GetAITargetsCount },
	{ "SetUnitToFollow", &luaUnit::SetUnitToFollow },
	{ "GetUnitToFollow", &luaUnit::GetUnitToFollow },
	{ "DismissPet", &luaUnit::DismissPet },
	{ "IsPet", &luaUnit::IsPet },
	{ "SetNextTarget", &luaUnit::SetNextTarget },
	{ "GetNextTarget", &luaUnit::GetNextTarget },
	{ "SetPetOwner", &luaUnit::SetPetOwner },
	{ "GetPetOwner", &luaUnit::GetPetOwner },
	{ "CalcToDistance", &luaUnit::CalcToDistance },
	{ "CalcAngle", &luaUnit::CalcAngle },
	{ "CalcRadAngle", &luaUnit::CalcRadAngle },
	{ "SetFacing", &luaUnit::SetFacing },
	{ "SetDeathState", &luaUnit::SetDeathState },
	{ "IsInvisible", &luaUnit::IsInvisible },
	{ "IsInvincible", &luaUnit::IsInvincible },
	{ "ResurrectPlayer", &luaUnit::ResurrectPlayer },
	{ "KickPlayer", &luaUnit::KickPlayer },
	{ "CanCallForHelp", &luaUnit::CanCallForHelp },
	{ "CallForHelpHp", &luaUnit::CallForHelpHp },
	{ "SetCreatureNameById", &luaUnit::SetCreatureName },
	{ "GetAITargets", &luaUnit::GetAITargets },
	{ "GetInRangePlayers", &luaUnit::GetInRangePlayers },
	{ "GetUnitByGUID", &luaUnit::GetUnitByGUID },
	{ "RemoveFromWorld", &luaUnit::RemoveFromWorld },
	{ "GetFaction", &luaUnit::GetFaction },
	{ "EnableMoveFly", &luaUnit::MoveFly },
	{ "SpellNonMeleeDamageLog", &luaUnit::SpellNonMeleeDamageLog },
	{ "DisableRespawn", &luaUnit::NoRespawn },
	{ "ModThreat", &luaUnit::ModThreat },
	{ "GetThreat", &luaUnit::GetThreatByPtr },
	{ "GetInRangeFriends", &luaUnit::GetInRangeFriends },
	{ "GetPowerType", &luaUnit::GetPowerType },
	{ "GetMapId", &luaUnit::GetMapId },
	{ "CalcDistance" , &luaUnit::CalcDistance },
	{ "AttackReaction", &luaUnit::AttackReaction },
	{ "EventCastSpell", &luaUnit::EventCastSpell },
	{ "IsPlayerMoving", &luaUnit::IsPlayerMoving },
	{ "IsPlayerAttacking", &luaUnit::IsPlayerAttacking },
	//{ "IsPlayerAtWar", &luaUnit::IsPlayerAtWar },
	{ "RemoveThreat", &luaUnit::RemoveThreatByPtr },
	{ "SetPlayerAtWar", &luaUnit::SetPlayerAtWar },
	{ "GetFactionStanding", &luaUnit::GetFactionStanding },
	{ "PlaySpellVisual", &luaUnit::PlaySpellVisual },
	{ "GetPlayerLevel", &luaUnit::GetPlayerLevel },
	{ "SetPlayerLevel", &luaUnit::SetPlayerLevel },
	{ "SetStanding", &luaUnit::SetPlayerStanding },
	{ "GetStanding", &luaUnit::GetStanding },
	{ "HasItem", &luaUnit::HasItem },
	{ "AdvanceSkill", &luaUnit::AdvanceSkill },
	{ "AddSkill", &luaUnit::AddSkill },
	{ "RemoveSkill", &luaUnit::RemoveSkill },
	{ "EnableFlyCheat", &luaUnit::FlyCheat },
	{ "AddAssistTarget", &luaUnit::AddAssistTargets },
	{ "GetCurrentSpellId", &luaUnit::GetCurrentSpellId },
	{ "GetPlayerRace", &luaUnit::GetPlayerRace },
	{ "RemoveAurasByMechanic", &luaUnit::RemoveAurasByMechanic },
	{ "RemoveAurasType", &luaUnit::RemoveAurasType },
	{ "AddAura", &luaUnit::AddAura },
	{ "SetAIState", &luaUnit::SetAIState },
	{ "InterruptSpell", &luaUnit::InterruptSpell },
	{ "RemoveStealth", &luaUnit::RemoveStealth },
	{ "IsPoisoned", &luaUnit::IsPoisoned },
	{ "SetStealthLevel", &luaUnit::SetStealth },
	{ "GetStealthLevel", &luaUnit::GetStealthLevel },
	{ "IsStealthed", &luaUnit::IsStealthed },
	{ "RemoveFlag", &luaUnit::RemoveFlag },
	{ "RegisterAIUpdateEvent", &luaUnit::RegisterAIUpdateEvent },
	{ "ModifyAIUpdateEvent", &luaUnit::ModifyAIUpdateEvent },
	{ "RemoveAIUpdateEvent", &luaUnit::RemoveAIUpdateEvent },
	{ "DeleteWaypoint", &luaUnit::deleteWaypoint },
	{ "PerformWorldDBQuery", &luaUnit::PerformWorldDBQuery },
	{ "PerformCharDBQuery", &luaUnit::PerformCharDBQuery },
	{ "DealGoldCost", &luaUnit::DealGoldCost },
	{ "DealGoldMerit", &luaUnit::DealGoldMerit },
	{ "CanUseCommand", &luaUnit::CanUseCommand },
	{ "DeMorph", &luaUnit::DeMorph },
	{ "Attack", &luaUnit::Attack },
	{ "GetTarget", &luaUnit::GetTarget },
	{ "GetSelection", &luaUnit::GetSelection },
	{ "SetMount", &luaUnit::SetMount },
	{ "StartQuest", &luaUnit::StartQuest },
	{ "FinishQuest", &luaUnit::FinishQuest },
	{ "RepairAllPlayerItems", &luaUnit::RepairAllPlayerItems },
	{ "SetKnownTitle", &luaUnit::SetKnownTitle },
	{ "LifeTimeKills", &luaUnit::LifeTimeKills },
	{ "HasTitle", &luaUnit::HasTitle },
	{ "GetMaxSkill", &luaUnit::GetMaxSkill },
	{ "GetCurrentSkill", &luaUnit::GetCurrentSkill },
	{ "HasSkill", &luaUnit::HasSkill },
	{ "GetGuildName", &luaUnit::GetGuildName },
	{ "ClearCooldownForSpell", &luaUnit::ClearCooldownForSpell },
	{ "HasSpell", &luaUnit::HasSpell },
	{ "ClearAllCooldowns", &luaUnit::ClearAllCooldowns },
	{ "ResetAllTalents", &luaUnit::ResetAllTalents },
	{ "GetAccountName", &luaUnit::GetAccountName },
//NA:	{ "GetGamemasterLevel", &luaUnit::GetGamemasterLevel },
	{ "SavePlayer", &luaUnit::SavePlayer },
	{ "HasQuest", &luaUnit::HasQuest },
	{ "RemovePvPFlag", &luaUnit::RemovePvPFlag },
	{ "RemoveNegativeAuras", &luaUnit::RemoveNegativeAuras },
	{ "GossipMiscAction", &luaUnit::GossipMiscAction },
	{ "EquipWeapons", &luaUnit::EquipWeapons },
	{ "Mount", &luaUnit::Mount },
	{ "Dismount", &luaUnit::Dismount },
	{ "AdvanceAllSkills", &luaUnit::AdvanceAllSkills },
	{ "GetTeam", &luaUnit::GetTeam },
	{ "Possess", &luaUnit::Possess },
	{ "Unpossess", &luaUnit::Unpossess },
	{ "StartTaxi", &luaUnit::StartTaxi },
	//Halestorm Added Commands
	{ "ChannelSpell", &luaUnit::ChannelSpell },
	{ "StopChannel", &luaUnit::StopChannel },
	{ "SetWorldState", &luaUnit::SetWorldState },
	{ "EnableFlight", &luaUnit::EnableFlight },
	{ "GetCoinage", &luaUnit::GetCoinage },
	{ "FlagPvP", &luaUnit::FlagPvP },
	{ "FlagWorldPvP", &luaUnit::FlagWorldPvP },
	{ "DisableWorldPvP", &luaUnit::DisableWorldPvP },
    { "GetDisplay", &luaUnit::GetDisplay },
    { "GetNativeDisplay", &luaUnit::GetNativeDisplay },
	{ "IsMounted", &luaUnit::IsMounted },
		//hypersniper added commands
		{ "GetGameTime", &luaUnit::GetGameTime },
		{ "PlaySoundToPlayer", &luaUnit::PlaySoundToPlayer },
		{ "GetDuelState", &luaUnit::GetDuelState }, 
		{ "SetPosition", &luaUnit::SetPosition},
		{ "CastSpellOnTarget", &luaUnit::CastSpellOnTarget},
		{ "GetLandHeight", &luaUnit::GetLandHeight},
		{ "QuestAddStarter", &luaUnit::QuestAddStarter},
		{ "QuestAddFinisher", &luaUnit::QuestAddFinisher},
		{ "SetPlayerSpeed", &luaUnit::SetPlayerSpeed},
		{ "GiveHonor", &luaUnit::GiveHonor},
		{ "SetBindPoint", &luaUnit::SetBindPoint},
		{ "SoftDisconnect", &luaUnit::SoftDisconnect},
		{ "SetZoneWeather", &luaUnit::SetZoneWeather},
		{ "SetPlayerWeather", &luaUnit::SetPlayerWeather},
		{ "SendPacketToPlayer", &luaUnit::SendPacketToPlayer},
		{ "SendPacketToZone", &luaUnit::SendPacketToZone},
		{ "SendPacketToWorld", &luaUnit::SendPacketToWorld},
		{ "SendPacketToInstance", &luaUnit::SendPacketToInstance},
		{ "PlayerSendChatMessage", &luaUnit::PlayerSendChatMessage},
		{ "GetDistanceYards", &luaUnit::GetDistanceYards},
		{ "VendorAddItem", &luaUnit::VendorAddItem},
		{ "VendorRemoveItem", &luaUnit::VendorRemoveItem},
		{ "VendorRemoveAllItems", &luaUnit::VendorRemoveAllItems},
		{ "CreatureHasQuest", &luaUnit::CreatureHasQuest},
		{ "SendVendorWindow", &luaUnit::SendVendorWindow},
		{ "SendTrainerWindow", &luaUnit::SendTrainerWindow},
		{ "SendInnkeeperWindow", &luaUnit::SendInnkeeperWindow},
		{ "SendBankWindow", &luaUnit::SendBankWindow},
		{ "SendAuctionWindow", &luaUnit::SendAuctionWindow},
		{ "SendBattlegroundWindow", &luaUnit::SendBattlegroundWindow},
		{ "GetInventoryItem", &luaUnit::GetInventoryItem},
		{ "GetInventoryItemById", &luaUnit::GetInventoryItemById},
		{ "PhaseSet", &luaUnit::PhaseSet},
		{ "PhaseAdd", &luaUnit::PhaseAdd},
		{ "PhaseDelete", &luaUnit::PhaseDelete},
		{ "GetPhase", &luaUnit::GetPhase},
		{ "AggroWithInRangeFriends", &luaUnit::AggroWithInRangeFriends},
		{ "GetPrimaryCombatTarget", &luaUnit::GetPrimaryCombatTarget},
		{ "MoveRandomArea", &luaUnit::MoveRandomArea},
		{ "SendLootWindow", &luaUnit::SendLootWindow},
		{ "GetRawGUID", &luaUnit::GetRawGUID},
		{ "AddLoot", &luaUnit::AddLoot},
		{ "SetPacified", &luaUnit::SetPacified},
		{ "GetUnitByRawGUID", &luaUnit::GetUnitByRawGUID},
		{ "PlaySpellVisualByRawGUID", &luaUnit::PlaySpellVisualByRawGUID},
		{ "SpawnVehicle", &luaUnit::SpawnVehicle},
		{ "SetVehicle", &luaUnit::SetVehicle},
		{ "GetVehicle", &luaUnit::GetVehicle},
		{ "RemoveFromVehicle", &luaUnit::RemoveFromVehicle},
		{ "GetVehicleSeat", &luaUnit::GetVehicleSeat},
		{ "IsVehicle", &luaUnit::IsVehicle},
		{ "GetPassengerCount", &luaUnit::GetPassengerCount},
		{ "MoveVehicle", &luaUnit::MoveVehicle},
	{ NULL, NULL },
};




RegType<GameObject> GOMethods[] = {
	{ "GetGUID", &luaGameObject::GetGUID },
	{ "GetName", &luaGameObject::GetName },
	{ "Teleport" , &luaGameObject::Teleport },
	{ "GetCreatureNearestCoords", &luaGameObject::GetCreatureNearestCoords },
	//{ "GetAreaID", &luaGameObject::GetAreaID },
	{ "AddItem", &luaGameObject::AddItem },
	{ "GetGameObjectNearestCoords", &luaGameObject::GetGameObjectNearestCoords },
	{ "GetItemCount", &luaGameObject::GetItemCount },
	{ "GetZoneId", &luaGameObject::GetZoneId },
	{ "GetClosestPlayer", &luaGameObject::GetClosestPlayer },
	{ "SpawnCreature", &luaGameObject::SpawnCreature },
	{ "SpawnGameObject", &luaGameObject::SpawnGameObject },
	{ "IsInWorld", &luaGameObject::IsInWorld },
	{ "GetSpawnX", &luaGameObject::GetSpawnX },
	{ "GetSpawnY", &luaGameObject::GetSpawnY },
	{ "GetSpawnZ", &luaGameObject::GetSpawnZ },
	{ "GetSpawnO", &luaGameObject::GetSpawnO },
	{ "GetInRangePlayersCount", &luaGameObject::GetInRangePlayersCount },
	{ "GetEntry", &luaGameObject::GetEntry },
	{ "SetOrientation", &luaGameObject::SetOrientation },
	{ "GetX", &luaGameObject::GetX },
	{ "GetY", &luaGameObject::GetY },
	{ "GetZ", &luaGameObject::GetZ },
	{ "GetO", &luaGameObject::GetO },
	{ "RemoveFromWorld", &luaGameObject::RemoveFromWorld },
	{ "CalcRadAngle", &luaGameObject::CalcRadAngle },
	{ "GetInstanceID", &luaGameObject::GetInstanceID },
	{ "GetInRangePlayers", &luaGameObject::GetInRangePlayers },
	{ "GetInRangeObjects", &luaGameObject::GetInRangeGameObjects },
	{ "IsInBack", &luaGameObject::IsInBack },
	{ "IsInFront", &luaGameObject::IsInFront },
	{ "GetMapId", &luaGameObject::GetMapId },
	{ "SetUInt32Value", &luaGameObject::SetUInt32Value },
	{ "SetUInt64Value", &luaGameObject::SetUInt64Value },
	{ "SetFloatValue", &luaGameObject::SetFloatValue },
	{ "GetUInt32Value", &luaGameObject::GetUInt32Value },
	{ "GetUInt64Value", &luaGameObject::GetUInt64Value },
	{ "GetFloatValue", &luaGameObject::GetFloatValue },
	{ "ModUInt32Value", &luaGameObject::ModUInt32Value },
	{ "CastSpell", &luaGameObject::CastSpell },
	{ "FullCastSpell", &luaGameObject::FullCastSpell },
	{ "CastSpellOnTarget", &luaGameObject::CastSpellOnTarget },
	{ "FullCastSpellOnTarget", &luaGameObject::FullCastSpellOnTarget },
	{ "GossipObjectCreateMenu", &luaGameObject::GossipCreateMenu },
	{ "GossipObjectMenuAddItem", &luaGameObject::GossipMenuAddItem }, 
	{ "GossipObjectSendMenu", &luaGameObject::GossipSendMenu },
	{ "GossipObjectComplete", &luaGameObject::GossipComplete },
	{ "GossipObjectSendPOI", &luaGameObject::GossipSendPOI },
	//{ "EventCastSpell", &luaGameObject::EventCastSpell },
	{ "RegisterAIUpdateEvent", &luaGameObject::RegisterAIUpdate },
	{ "ModifyAIUpdateEvent", &luaGameObject::ModAIUpdate },
	{ "RemoveAIUpdateEvent", &luaGameObject::RemoveAIUpdate },
	{ "PerformWorldDBQuery", &luaGameObject::PerformWorldDBQuery },
	{ "PerformCharDBQuery", &luaGameObject::PerformCharDBQuery },
	{ "Activate", &luaGameObject::Activate },
	{ "IsActive", &luaGameObject::IsActive },
	//All three of these do the same thing.
	{ "ObjectDespawn", &luaGameObject::DespawnObject }, //'cause it was announced on SVN like that
	{ "Despawn", &luaGameObject::DespawnObject },
	{ "DespawnObject", &luaGameObject::DespawnObject },
	//hypersniper's
		{ "GetGameTime", &luaGameObject::GetGameTime },
		{ "GetLandHeight", &luaGameObject::GetLandHeight},
		{ "SetZoneWeather", &luaGameObject::SetZoneWeather},
		{ "PhaseSet", &luaGameObject::PhaseSet},
		{ "PhaseAdd", &luaGameObject::PhaseAdd},
		{ "PhaseDelete", &luaGameObject::PhaseDelete},
		{ "GetPhase", &luaGameObject::GetPhase},
		{ "InitPacket", &luaGameObject::InitPacket},
		{ "AddDataToPacket", &luaGameObject::AddDataToPacket},
		{ "SendPacketToZone", &luaGameObject::SendPacketToZone},
		{ "SendPacketToWorld", &luaGameObject::SendPacketToWorld},
		{ "SendPacketToInstance", &luaGameObject::SendPacketToInstance},
		{ "GetRawGUID", &luaGameObject::GetRawGUID},
		{ "AddLoot", &luaGameObject::AddLoot},

	/*{ "ModFloatValue", &luaGameObject::ModFloatValue },	
	{ "InitPacket", &luaGameObject::InitPacket },
	{ "AddDataToPacket", &luaGameObject::AddDataToPacket },
	{ "AddGuidDataToPacket", &luaGameObject::AddGuidDataToPacket },
	{ "SendData", &luaGameObject::SendData },*/

	{ NULL, NULL },
};




/*
int PerformDBQueryIdea?!?^^(lua_State * L, caller * ptr)
{
	const bool * qDB = luaL_checkboolean(L,1); //true: World, false: Char
	const char * qStr = luaL_checkstring(L,2);
	if(!qStr) return 0;
	if (!Config.OptionalConfig.GetBoolDefault("LUAppArc", "AllowDBQueries", false)) {
		lua_pushnumber(L, 0); //0=Disabled
		return 1;
	}
	if (qDB) {
		QueryResult * result = WorldDatabase.Query(qStr);
	} else {
		QueryResult * result = CharacterDatabase.Query(qStr);
	}
	if (result) {
		lua_pushnumber(L, 1); //1=GotData
	} else lua_pushnumber(L, 2); //2=NoData
	return 0;
}
*/
