# Copyright (C) 2014-2015 AscEmu Team <http://www.ascemu.org>

# general
set(ASCEMU_SCRIPTLIB_PATH "Script_Bin" CACHE PATH "The directory for AscEmu Modules." )
option(EXTRA_SCRIPTS2 "Build AscEmu Dev Modules2." ON)
#option(BUILD_ASCEMUSCRIPTS "Build AscEmu Script_Bin." ON)
#option(BUILD_TOOLS "Build AscEmu tools." OFF)
#option(BUILD_EXTRAS "Build AscEmu extra." OFF)
option(BUILD_ANNOUNCE "Build ascAnnounce." ON)
option(BUILD_ANNOUNCEMENT "Build ascAnnouncement." ON)
option(BUILD_ANTIPVPATMALL "Build ascAntiPvPAtMall." ON)
#option(BUILD_AUTOMAILER "Build ascAutoMailer." ON)
option(BUILD_AVM "Build ascAVM." ON)
option(BUILD_BATTLEMAGE "Build ascBattleMage." ON)
option(BUILD_BGNPC "Build ascBGNPC." ON)
option(BUILD_BUFFER "Build ascBuffer." ON)
option(BUILD_CALADRIELTELEPORTER "Build ascCaladrielTeleporter." ON)
option(BUILD_COTTAXI "Build ascCOTTAXI." ON)
option(BUILD_CUSTOMNPC "Build ascCustomNPC." ON)
option(BUILD_DISCONNECT "Build ascDisconnect." ON)
option(BUILD_DPANEL "Build ascDPanel." ON)
option(BUILD_ENTERWORLD "Build ascEnterWorld." ON)
option(BUILD_EVENTPORTER1 "Build ascEventporter1." ON)
option(BUILD_EVENTPORTER2 "Build ascEventporter2." ON)
option(BUILD_FREEMONEYNPC "Build ascFreeMoneyNPC." ON)
option(BUILD_FRIENDPORTER "Build ascFriendPorter." ON)
option(BUILD_GANKGUARD "Build ascGankGuard." ON)
option(BUILD_GETOUT_HYJAL "Build ascgetout_hyjal." ON)
option(BUILD_GLOBALNPC "Build ascGlobalNPC." ON)
option(BUILD_GMSTONE "Build ascGmStone." ON)
option(BUILD_GMSTONE2 "Build ascGmStone2." ON)
option(BUILD_GMHELPER "Build ascGMHelper." ON)
option(BUILD_GUILDCREATE "Build ascGuildCreate." ON)
option(BUILD_HARALDTELEPORTER "Build ascHaraldTeleporter." ON)
option(BUILD_HEALNPC "Build ascHealNPC." ON)
option(BUILD_HOUSENPC "Build ascHouseNPC." ON)
option(BUILD_INTO_HYJAL "Build ascinto_hyjal." ON)
option(BUILD_LEGORIONTELEPORTER "Build ascLegorionTeleporter." ON)
option(BUILD_LVLTOKEN "Build ascLvlToken." ON)
option(BUILD_MAXSKILL "Build ascMaxSkill." ON)
option(BUILD_MCGOYVER "Build ascMcGoyver." ON)
option(BUILD_MENU "Build ascMenu." ON)
option(BUILD_MMOPRO1 "Build ascMMOPRO1." ON)
option(BUILD_MONESTERPORTERNPC "Build ascMonsterporternpc." ON)
option(BUILD_MORPHER "Build ascMorpher." ON)
option(BUILD_MORPHERNPC "Build ascMorpherNPC." ON)
option(BUILD_MOUNTER "Build ascMounter." ON)
option(BUILD_MOUNTNPC "Build ascMountNPC." ON)
option(BUILD_NOOBHELPER "Build ascNoobHelper." ON)
option(BUILD_ONFIRSTENTERWORLD "Build ascOnFirstEnterWorld." ON)
option(BUILD_ONGUILDJOIN "Build ascOnGuildjoin." ON)
option(BUILD_ONLOGOUTREQUEST "Build ascOnLogoutReguest." ON)
option(BUILD_ONPLAYERFIRSTENTERWORLD "Build ascOnPlayerFirstEnterWorld." ON)
option(BUILD_PAYNPC "Build ascPayNPC." ON)
option(BUILD_PLAYERXP "Build ascPlayerXP." ON)
option(BUILD_PLAYERMOVIEONFIRSTLOGIN "Build ascPlayMovieOnFirstLogin." ON)
option(BUILD_POWERTELEPORTER "Build ascPowerTeleporter." ON)
option(BUILD_PROFESSIONS "Build ascProfessions." ON)
option(BUILD_PROTCTIONONLOGIN "Build ascProtctionOnLoging." ON)
option(BUILD_PROXIMITYHEAL "Build ascProximityHeal." ON)
option(BUILD_PVP_SYSTEM "Build ascPVP_SYSTEM." ON)
option(BUILD_PVPANNER "Build ascPvPAnner." ON)
option(BUILD_PVPMONEYNPC "Build ascPvpMoneynpc." ON)
option(BUILD_PVPTOKEN "Build ascPvPToken." ON)
option(BUILD_RELOADER "Build ascReloader." ON)
option(BUILD_REPUTATIONNPC "Build ascReputationnpc." ON)
option(BUILD_REVIVE "Build ascRevive." ON)
option(BUILD_RUNEBOOK "Build ascRunebook." ON)
option(BUILD_SKILLNPC "Build ascSkillnpc." ON)
option(BUILD_TELECOPTER "Build ascTeleCopter." ON)
option(BUILD_TITLENPC "Build ascTitlenpc." ON)
option(BUILD_TITLEVENDOR2 "Build ascTitleVendor2." ON)
option(BUILD_TOKENS "Build ascTokens." ON)
option(BUILD_UBERMORPHER "Build ascUberMorpher." ON)
option(BUILD_VEKJIK_GOSSIP "Build ascVekjik_Gossip." ON)
option(BUILD_WHICHDOCTOR "Build ascWitchDoctor." ON)
option(BUILD_WEAPONDROPPER "Build ascWeaponDropper." ON)
option(BUILD_WISHINGSTONE "Build ascWishingStone." ON)
#set(ASCEMU_TOOLS_PATH "tools" CACHE PATH "The directory where you want the tools installed.")
option(BUILD_WITH_WARNINGS "Enable/Disable warnings on compilation" OFF)
option(USE_PCH "Enable precompiled headers - it will reduce compilation time" ON)
# platform specific
if(WIN32)
    set(VISUALSTUDIO_COMPILERHEAPLIMIT 460 CACHE STRING "Visual Studio compiler heap limit. Ignore on darwin and unix platforms.")
    set(ASCEMU_CONFIGSFILE_PATH configs CACHE PATH "Path to AscEmu configs." )
else()
    set(ASCEMU_CONFIGSFILE_PATH etc CACHE PATH "Path to AscEmu configs." )
endif()
