# Copyright (C) 2014-2015 AscEmu Team <http://www.ascemu.org>

# general
set(ASCEMU_SCRIPTLIB_PATH "modules" CACHE PATH "The directory for AscEmu modules." )
option(BUILD_ASCEMUSCRIPTS "Build AscEmu modules." ON)
option(BUILD_TOOLS "Build AscEmu tools." OFF)
option(BUILD_EXTRAS "Build AscEmu extra." OFF)
#option(BUILD_DEATHKNIGHT "Build ascDeathKnight." ON)
option(BUILD_EVENTSCRIPTS "Build ascEventScripts." ON)
option(BUILD_EVENTDARKPORTAL "Build ascEventDarkPortal." ON)
option(BUILD_SCRIPTS2 "Build AscEmu Dev modules2." OFF)
option(BUILD_INSTANCESCRIPTS "Build ascInstanceScripts." ON)
option(BUILD_RAIDSSCRIPTS "Build ascRaidsScripts." ON)
option(BUILD_SERVERSTATUSPLUGIN "Build ascServerStatusPlugin." ON)
option(BUILD_EXTRASCRIPTS "Build ascExtraScripts." ON)
option(BUILD_GOSSIPSCRIPTS "Build ascGossipScripts." ON)
option(BUILD_QUESTSCRIPTS "Build ascQuestScripts." ON)
option(BUILD_MISCSCRIPTS "Build ascMiscScripts." ON)
option(BUILD_LUAENGINE "Build LuaEngine." ON)
option(BUILD_LUABRIDGE "Build luabridge." OFF)
#option(DEV_SOURCES "Build AscEmu Dev Script_Bin." OFF)
set(ASCEMU_TOOLS_PATH "tools" CACHE PATH "The directory where you want the tools installed.")
option(BUILD_WITH_WARNINGS "Enable/Disable warnings on compilation" OFF)
option(USE_PCH "Enable precompiled headers - it will reduce compilation time" ON)
# platform specific
if(WIN32)
    set(VISUALSTUDIO_COMPILERHEAPLIMIT 460 CACHE STRING "Visual Studio compiler heap limit. Ignore on darwin and unix platforms.")
    set(ASCEMU_CONFIGSFILE_PATH configs CACHE PATH "Path to AscEmu configs." )
else()
    set(ASCEMU_CONFIGSFILE_PATH etc CACHE PATH "Path to AscEmu configs." )
endif()
